export const materiales= [
    { //1
        nombre: "Papel y Cartón",
        imagen: "material_Papel y carton.png",
        codColor: "#A1887F",
        descripcion: "Residuos de papel y cartón que se pueden reutilizar para fabricar nuevos productos. El papel y el cartón se componen principalmente de celulosa, una sustancia que se obtiene de la madera de los árboles. Al reciclar el papel y el cartón, se evita la tala de muchos árboles y se ahorran recursos como el agua, el petróleo y la energía. Además, se reduce la emisión de gases de efecto invernadero como el CO2, que contribuyen al calentamiento global.",
        unidadMedida: "kilogramo",
        monedasUnidad: 2,
    },
    { //2
        nombre: "Plástico",
        imagen: "material_Plastico.png",
        codColor: "#B2DFDB",
        descripcion: "El plástico es un material sintético que se puede moldear en diferentes formas y que tiene muchas aplicaciones en la industria, la medicina, la construcción, el transporte y la vida cotidiana. Sin embargo, el plástico también tiene un gran impacto negativo en el medio ambiente, ya que tarda mucho tiempo en degradarse y contamina el suelo, el agua y el aire. Por eso, es importante reciclar el plástico para reducir su consumo y aprovechar sus propiedades.",
        unidadMedida: "kilogramo",
        monedasUnidad: 4,
    },
    { //3
        nombre: "Telas y Textiles",
        imagen: "material_Telas y Textiles.jpg",
        codColor: "#EDED5D",
        descripcion: "Telas y textiles son materiales que se usan para fabricar ropa, cortinas, tapices, alfombras y otros productos. Estos materiales pueden ser de origen natural, como el algodón, la lana, la seda o el lino, o de origen sintético, como el poliéster, el nylon o el acrílico. El reciclaje de telas y textiles es una forma de aprovechar los residuos de estos materiales y transformarlos en nuevos productos o materias primas.",
        unidadMedida: "kilogramo",
        monedasUnidad: 4,
    },
    { //4
        nombre: "Vidrio",
        imagen: "material_vidrio.jpg",
        codColor: "#9CEDF1",
        descripcion: "El vidrio es un material que se puede reciclar muchas veces sin perder su pureza o calidad. El reciclaje del vidrio consiste en recuperar los envases de vidrio usados y transformarlos en nuevos productos o materias primas. El reciclaje del vidrio tiene muchos beneficios para el medio ambiente y la economía,",
        unidadMedida: "kilogramo",
        monedasUnidad: 2,
    },
    { //5
        nombre: "Chatarra y Metales",
        imagen: "material_Chatarra y metales.png",
        codColor: "#F9A825",
        descripcion: "El vidrio es un material que se puede reciclar muchas veces sin perder su pureza o calidad. El reciclaje del vidrio consiste en recuperar los envases de vidrio usados y transformarlos en nuevos productos o materias primas. El reciclaje del vidrio tiene muchos beneficios para el medio ambiente y la economía, el proceso de reciclaje de la chatarra y los metales varía según el tipo de material.",
        unidadMedida: "kilogramo",
        monedasUnidad: 6,
    },
    { //6
        nombre: "Aparatos Eléctricos y Electrónicos",
        imagen: "material_aparatos electricos y electronicos.jpg",
        codColor: "#303F9F",
        descripcion: "Los aparatos eléctricos y electrónicos son aquellos que funcionan con electricidad o baterías y que tienen componentes electrónicos, como circuitos, chips, pantallas, etc. Estos aparatos pueden ser desde ordenadores, teléfonos móviles, televisores, cámaras, hasta electrodomésticos, juguetes, herramientas o instrumentos musicales, además, el reciclaje de los aparatos eléctricos y electrónicos es muy importante para el medio ambiente y la economía, ya que estos aparatos contienen materiales valiosos que se pueden recuperar y reutilizar, como metales, plásticos, vidrio o fibra óptica.",
        unidadMedida: "kilogramo",
        monedasUnidad: 8,
    }
]